### PR TITLE
Dont Install node.js from source

### PR DESCRIPTION
**Pull request by leonelgalan**
There has to be a better way of installing the latest version of node and npm that doesn't involve building from source.

### CODE REVIEW

**Comment by leonelgalan** [comment]
* Ok, this started with me trying to get the FE running (revising: how we install node, it's not from source; update npm and build a FE app), but I had to "fix" (encoding issue) PostgreSQL to successfully run my app.
* _smashing-dev-tool_ wasn't ready for prime time.
* I found an issue related to dependencies (See https://github.com/smashingboxes/tape/issues/34)

**Comment by leonelgalan** [comment]
:warning: Don't merge yet :warning:

**Comment by BrandonMathis** [comment]
:rotating_light: :rotating_light: :rotating_light: :rotating_light: :rotating_light: :rotating_light: :rotating_light:

**Comment by BrandonMathis** [comment]
im gonna review this now

**Comment by leonelgalan** [comment]
Ready for review! Do not merge until my build finishes. I want to make sure `bundle exec tape ansible everything` works as advertised!

**Comment by leonelgalan** [comment]
We are good! It took may vagrant 42s to boot and 27m 50s to run ansible (28m 22s total)

`date && vagrant destroy --force && vagrant up && date && bundle exec tape ansible everything -l vagrant && date && open "http://localhost:8080/" && date && say -v "Good News" "Deployed"`

**Pull request merged**
