### PR TITLE
Adds memcached

### PR DESCRIPTION
**Pull request by leonelgalan**
Allows to use memcached to enable caching using dalli.

### CODE REVIEW

**Comment by BrandonMathis** [comment]
Have you tried building a fresh ansible box and standing up a simple rails app from this branch?

I have been using this repo to test smashing_boxer since we currently don't have any automated testing

https://github.com/BrandonMathis/vanilla-rails-app

**Comment by leonelgalan** [comment]
No, but I did use it on `malartu` by running `everything`

**Comment by BrandonMathis** [comment]
@leonelgalan ansible-galaxy this dude :+1:

**Comment by BrandonMathis** [comment]
@leonelgalan what is the status of this pr. Do we still want to merge?

**Comment by leonelgalan** [comment]
Needs rebase.

**Comment by leonelgalan** [comment]
I just installed weaveup on my server (weaveups new dev) using this, works like a charm! :neckbeard:

**Comment by BrandonMathis** [comment]
doesn't memcached need to be restarted after every deploy?

**Comment by leonelgalan** [comment]
No, you will destroy the cache that way. It might need, but that's up to the developer.

**Pull request merged**
